spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projet3?createDatabaseIfNotExist=true
    username: ilyess
    password: Themechanist1

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
logging:
  level:
    org :
      springframework:
        security: DEBUG
